global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: host-machine
    static_configs:
      - targets: ["host-exporter:9100"]
remote_write:
  - url: "grafana:3000"
    basic_auth:
      username: "admin"
      password: "admin"