version: "3.7"
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/config/:/conf/prometheus
      - ./prometheus/mount/:/prometheus
    command:
      - "--web.enable-lifecycle" # Enable prometheus api server reload
      - "--config.file=/conf/prometheus/prometheus.yml"
    restart: unless-stopped
    ports:
      - "9090:9090"
    networks:
      - sandbox
  host-exporter:
    image: prom/node-exporter
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/:/rootfs:ro"
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs' # For Host machine metric export
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    ports:
      - "9100:9100"
    networks:
      - sandbox
  granafa:
    image: bitnami/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    ports:
      - "3000:3000"
    networks:
      - sandbox
networks:
  sandbox:
    driver: bridge